app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from aplicacion.views import *
from aplicacion.Views.ventaView import *
from aplicacion.Views.loteView import *
from aplicacion.Views.productoView import *
from aplicacion.Views.cajaView import *
from aplicacion.Views.reporteView import *
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', nuevaVenta),
    url(r'^login/$', Login),
    url(r'^logout/$', Logout),
    url(r'^home/$', nuevaVenta),
    ################## VENTA ##############################
    url(r'^venta/$', nuevaVenta),
    url(r'^venta/nuevo/$', nuevaVenta),
    url(r'^venta/detalle/(?P<id_venta>\d+)/$', nuevaVenta),
    url(r'^venta/insertar/$', insertarVenta),
    url(r'^venta/imprimir/$', imprimirVenta),
    url(r'^venta/anular/(?P<id_venta>\d+)/$$', anularVenta),
    url(r'^venta/imprimir/(?P<id_venta>\d+)/$', imprimirVentaGET),
    url(r'^venta/listar', login_required(VentaList.as_view()), name='mascota_listar'),

    ################## PRODUCTO ########################
    url(r'^producto/nuevo/$', nuevoProducto),
    url(r'^producto/detalle/$', nuevoProducto),
    url(r'^producto/editar/$', nuevoProducto),
    #url(r'^producto/listar/$', listarProducto),
    url(r'^producto/buscar/$', BuscarProducto),
    url(r'^producto/listar', login_required(ProductoList.as_view()), name='producto_listar'),
    url(r'^producto/editar/(?P<pk>\d+)/$', login_required(ProductoUpdate.as_view()), name='producto_editar'),
    ################## REPORTES ###########################(?P<pk>\d+)/
    url(r'^reporte/venta/$', reporteVenta),
    url(r'^reporte/caja/$', reporteCierreCaja),
    url(r'^reporte/venta/$', reporteVenta),
    ################## LOTE ###########################(?P<pk>\d+)/

    url(r'^lote/listar/$', login_required(LoteList.as_view()), name='producto_listar'),
    url(r'^lote/nuevo/$', nuevoLote),

    ################## CAJA ###############################
    url(r'^caja/apertura/$', registrarAperturacaja),
    url(r'^caja/cierre/$', registrarCierrecaja),
    #url(r'^Caja/movimiento/$', registrarOperacion),

    ####################################################
    #Funciones de INICIO
    url(r'^venta/descontar/$', descontarVenta),
    url(r'^lote/ingresar/$', ingresarLote),

]

aplicacion/models.py
from __future__ import unicode_literals

from django.db import models


class Caja(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Aperturacaja(models.Model):
    fecha  = models.DateTimeField(auto_now_add=True, blank=True)
    monto  = models.FloatField()
    activo = models.BooleanField(blank=True,default=True)
    estado = models.BooleanField(blank=True,default=True)
    caja   = models.ForeignKey('Caja',on_delete=models.CASCADE)  # Field name made lowercase.

class Cierrecaja(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    estado = models.BooleanField(blank=True,default=True)
    aperturacaja = models.ForeignKey(Aperturacaja,on_delete=models.CASCADE)  # Field name made lowercase.

class Producto(models.Model):
    nombre       = models.CharField(max_length=45)
    codigo       = models.CharField(max_length=45, blank=True, null=True)
    unidad       = models.CharField(max_length=10, blank=True, null=True)
    cantidad     = models.FloatField(default=0,blank=True, null=True)
    imagen       = models.ImageField(blank=True, null=True)#upload_to='%Y/%m/%d',
    url          = models.CharField(max_length=100, blank=True, null=True)
    precioxmenor = models.FloatField(blank=True)
    precioxmayor = models.FloatField(blank=True, null=True)
    estado       = models.BooleanField(blank=True,default=True)

    class Meta:
        ordering = ["nombre"]
    def __str__(self):
        return self.nombre

class Lote(models.Model):
    fecha      = models.DateTimeField(auto_now_add=True, blank=True)
    modificado = models.DateTimeField(auto_now=True, blank=True)
    proveedor  = models.CharField(max_length=45)  # Field name made lowercase.
    productos  = models.ManyToManyField(Producto)
    estado     = models.BooleanField(blank=True,default=True)

from django.contrib.auth.models import User
class Anulacionventa(models.Model):
    fecha        = models.DateTimeField(auto_now_add=True, blank=True)
    descripcion  = models.TextField(blank=True,null=True)
    usuario      = models.ForeignKey(User,on_delete=models.CASCADE)
    estado       = models.BooleanField(blank=True,default=True)

class Venta(models.Model):
    fecha          = models.DateTimeField(auto_now_add=True, blank=True)
    monto          = models.FloatField(blank=True, null=True)
    nrecibo        = models.CharField(max_length=45, blank=True, null=True)
    productos      = models.ManyToManyField(Producto)
    aperturacaja   = models.ForeignKey(Aperturacaja,on_delete=models.CASCADE, blank=True, null=True)  # Field name made lowercase.
    anulacionventa = models.ForeignKey(Anulacionventa,on_delete=models.CASCADE, blank=True, null=True, default = '')
    estado         = models.BooleanField(blank=True,default=True)

    class Meta:
        ordering = ["-fecha"]
    def __str__(self):
        cadena = str(self.fecha)+" - "+str(self.monto)
        return cadena

class Ventaproductos(models.Model):
    fecha        = models.DateTimeField(auto_now_add=True, blank=True)
    modificacion = models.DateTimeField(auto_now=True, blank=True)
    cantidad     = models.FloatField(default=0,blank=True, null=True)
    precioventa  = models.FloatField(default=0,blank=True, null=True)
    venta        = models.ForeignKey(Venta,on_delete=models.CASCADE)
    producto     = models.ForeignKey(Producto,on_delete=models.CASCADE)
    activo       = models.BooleanField(blank=True,default=True)
    estado       = models.BooleanField(blank=True,default=True)

    class Meta:
        managed = False
        db_table = 'aplicacion_venta_productos'

class LoteProductos(models.Model):
    fecha        = models.DateTimeField(auto_now_add=True, blank=True)
    modificacion = models.DateTimeField(auto_now=True, blank=True)
    cantidad     = models.FloatField(default=0,blank=True, null=True)
    lote        = models.ForeignKey(Lote,on_delete=models.CASCADE)
    producto     = models.ForeignKey(Producto,on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'aplicacion_lote_productos'

aplicacion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from app import settings
from django.contrib.auth.decorators import login_required
# Create your views here.
from aplicacion.models import *
from django.views.decorators.csrf import csrf_exempt
import json

def Login(request):
    next = request.GET.get('next', '/home/')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        #print user
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(next)
            else:
                return HttpResponse("Inactive user.")
        else:
            return HttpResponseRedirect(settings.LOGIN_URL)

    return render(request, "login/login.html", {'redirect_to': next})

def Logout(request):
    logout(request)
    return HttpResponseRedirect(settings.LOGIN_URL)

@login_required
def Home(request):
    return render(request, "inicio/index.html", {'redirect_to': next})

def Prueba(request):
    oCaja = Caja.objects.filter(estado=1)
    #print oCaja
    return HttpResponse(json.dumps({'exito':1}), content_type="application/json")


@login_required
def descontarVenta(request):
    if request.method == 'GET':
        oVentas = Venta.objects.filter(estado=True)
        for oVenta in oVentas:
            for oProductoVenta in oVenta.productos.filter(estado=True):
                #print (oProductoVenta.id)
                #print (oProductoVenta.cantidad)
                try:
                    oProducto = Producto.objects.get(id= oProductoVenta.id)
                    oVentaproductos = Ventaproductos.objects.get(producto = oProducto, venta = oVenta)
                    oProducto.cantidad=oProducto.cantidad - oVentaproductos.cantidad
                    oProducto.save()
                    print ("Correcto")
                except:
                    print ("error en producto.id: ")
                    print (oProductoVenta.id)
        return HttpResponse("Listo!")

@login_required
def ingresarLote(request):
    if request.method == 'GET':
        oLotes = Lote.objects.filter(estado=True)
        for oLote in oLotes:
            for oProductoLote in oLote.productos.filter(estado=True):
                #print (oProductoLote.id)
                try:
                    oProducto = Producto.objects.get(id= oProductoLote.id)
                    oLoteProducto = LoteProductos.objects.get(lote=oLote,producto = oProducto)
                    oProducto.cantidad=oProducto.cantidad + oLoteProducto.cantidad
                    oProducto.save()
                    #print (oProductoLote.id)
                    #print ("Correcto")
                    print (oProducto.cantidad)
                except:
                    print ("error en producto.id: ")
                    print (oProductoVenta.id)
        return HttpResponse("Listo!")

aplicacion/templates/lote/nuevo.html
{% extends "base.html" %}
{% block imports %}
<script type="text/javascript" src="/static/js/lote.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $( "#cantidad" ).focus();
        //$( "#inpt-producto" ).focus();
        $('cantidad').prop('disabled', true);
        $( "#inpt-producto" ).autocomplete({
            source: function (request, response) {

                var datos = {nombreProducto: $("#inpt-producto").val()};
                var sendData = JSON.stringify(datos);
                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "/producto/buscar/",
                    data: sendData,
                    contentType: "application/json; charset=utf-8",
                    async: false,
                    cache: false,
                    CrossDomain: true,

                    success: function (result) {
                    var ListasProductos = result['productos'];
                    response($.map(ListasProductos, function (item) {
                        return {
                            label: item.nombre,
                            idproducto: item.nombre,
                            codigo: item.codigo,
                            Id: item.id
                            };
                        }));
                    }
                });
            },
            minLength: 2,
            select: function (event, ui) {
                $.data(document.body, 'idproducto', ui.item.Id);//guardar el id en memoria el $.data guarda en memoria
                $( "#codigo" ).val( ui.item.codigo);

                $( "#cantidad" ).focus();
                $( "#cantidad" ).focus();
                var iDPro = ui.item.Id;
                //agregar();
            }
        });
  });
</script>

 <style>
    ul.ui-autocomplete {
        z-index: 1100;
    }
    #content{
        position: absolute;
        min-height: 50%;
        width: 80%;
        top: 20%;
        left: 5%;
    }

    .selected{
        cursor: pointer;
    }
    .selected:hover{
        background-color: #0585C0;
        color: white;
    }
    .seleccionada{
        background-color: #0585C0;
        color: white;
    }
</style>
{% endblock %}


{% block title %}
Nueva Venta
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Nuevo Lote</h3>
                <br>
                <label for="id_nombre">Cantidad:</label>
                <br>
                <input type="number" name="cantidad" id="cantidad" required="" class="form-control" >
                <label for="id_nombre">Producto:</label>
                <br>
                <input type="text" name="inpt-producto" id="inpt-producto" required="" class="form-control" maxlength="45" onkeyup="if(event.keyCode == 13) InsertarLote()">
                <br>
                <label for="id_nombre">Código:</label>
                <br>
                <input type="text" name="codigo" id="codigo" required="" class="form-control" disabled="disabled">
                <br>
                
                <button id="bt_add" class="btn btn-success">Agregar</button>
                <button id="bt_del" class="btn btn-warning">Eliminar</button>
                <button id="bt_delall" class="btn btn-danger">Eliminar todo</button>

                    <div class="row">
                        <div class="form-group">
                            <label ><center>Concepto Operación</center></label>
                            <table id="tabla" class="table table-bordered">
                            <thead>
                                <tr>
                                    <td>Nº</td>
                                    <td>Cantidad</td>
                                    <td>Cod. Producto</td>
                                    <td>Nombre</td>
                                </tr>
                            </thead>
                            </table>

                            <br>
                        </div>
                            <br>

                        <button id="bt_GenerarLote" class="btn btn-success">Crear Lote</button>

                    </div>

                    <div class="row">
                        <div class="form-group">
                            <div class="col-sm-8 col-md-8 col-lg-6">
                                <div id="tabs" style="display:none;">
                                    <table id="listaProducto"></table>
                                    <div id="pagerlistaProducto"  style="text-align: center;"></div>
                                </div>
                            </div>

                            <div class="col-sm-2 col-md-2 col-lg-4">

                            </div>
                        </div>
                    </div>


    </div>
{% endblock %}